/*
* wrapper for header generated by codesynthesis xsd
*/

#ifndef MAZECOM__HPP
#define MAZECOM__HPP

#include <iostream>

//resolve conflict between WinError.h and mazeCom.hpp, 
//could lead to problem when including this header before other headers (and possibly other cases)
//but no control over names used in xsd
#undef ERROR
#undef NOERROR

#include "mazeCom.hpp"

void print(std::ostream& os, boardType& b);

#endif